"""empty message

Revision ID: 6dc6218bd39e
Revises: 85a4c12c3084
Create Date: 2024-11-16 11:48:29.952208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc6218bd39e'
down_revision = '85a4c12c3084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_token', sa.String(length=600), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_token')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint('institutions_code_key', type_='unique')
        batch_op.drop_constraint('institutions_icon_key', type_='unique')
        batch_op.drop_constraint('institutions_name_key', type_='unique')
        batch_op.drop_constraint('institutions_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('consent_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_token', sa.VARCHAR(length=600), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('institutions_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('institutions_name_key', ['name'])
        batch_op.create_unique_constraint('institutions_icon_key', ['icon'])
        batch_op.create_unique_constraint('institutions_code_key', ['code'])

    op.drop_table('connections')
    # ### end Alembic commands ###
