"""empty message

Revision ID: ba8ab5283c67
Revises: 45825af53616
Create Date: 2024-11-01 16:18:10.950282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8ab5283c67'
down_revision = '45825af53616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yapily_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['yapily_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('yapily_id')

    # ### end Alembic commands ###
