"""empty message

Revision ID: f619774e8f1b
Revises: 59fe15e0fc26
Create Date: 2024-10-11 17:22:08.965075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f619774e8f1b'
down_revision = '59fe15e0fc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixed_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('real_amount', sa.Float(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('next_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixed_expenses')
    # ### end Alembic commands ###
