"""empty message

Revision ID: fe6ee9d2e15c
Revises: 6dc6218bd39e
Create Date: 2024-11-16 11:58:47.961831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6ee9d2e15c'
down_revision = '6dc6218bd39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint('connections_consent_token_key', type_='unique')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['icon'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connection_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('sources_institution_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'connections', ['connection_id'], ['id'])
        batch_op.drop_column('institution_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sources_institution_id_fkey', 'institutions', ['institution_id'], ['id'])
        batch_op.drop_column('connection_id')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_unique_constraint('connections_consent_token_key', ['consent_token'])

    # ### end Alembic commands ###
